[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geopops"
version = "0.2.0"
description = "GeoPops"
readme = "README.md"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE", "NOTICE"]
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
]
dependencies = [
  "curl-cffi>=0.13.0",
  "geopandas",
  "networkx",
  "numpy",
  "pandas>=2.3.2",
  "pyarrow>=14.0.0",
  "python-dotenv>=1.0.0",
  "requests>=2.32.5",
  "sciris",
  "scipy",
  "shapely",
  "starsim>=3.0.3",
  "urllib3>=2.5.0",
]

[project.optional-dependencies]
dev = [
  "ipykernel",
]

[tool.setuptools.packages.find]
where = ["src"]

# patterns are relative to the *package root* (src/geopops)
[tool.setuptools.package-data]
geopops = ["geocorr/*", "julia/*", "config.json"]
